<a href="https://colab.research.google.com/github/MDTanveerAlam1/ExcelR/blob/main/CHI_SQUARE_TEST_Part_1_%2C_Assignment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**State the Hypotheses:**

*Null Hypothesis (H0)*: There is no significant association between the type of smart home device purchased (Smart Thermostats vs. Smart Lights) and the customer satisfaction level.

*Alternative Hypothesis (H1)*: There is a significant association between the type of smart home device purchased (Smart Thermostats vs. Smart Lights) and the customer satisfaction level.

In [30]:
import pandas as pd
import numpy as np
import scipy.stats as stats

In [31]:
# Data
data = {'Satisfaction': ['Very Satisfied', 'Satisfied', 'Neutral', 'Unsatisfied', 'Very Unsatisfied'],
        'Smart Thermostat': [50, 80, 60, 30, 20],
        'Smart Light': [70, 100, 90, 50, 50]}

1. Creates a DataFrame from the provided data.

2. Generates a contingency table.

In [32]:
# DataFrame
df = pd.DataFrame(data)
print(df)

# Table format
contingency_table = pd.crosstab(df['Satisfaction'], [df['Smart Thermostat'], df['Smart Light']])

       Satisfaction  Smart Thermostat  Smart Light
0    Very Satisfied                50           70
1         Satisfied                80          100
2           Neutral                60           90
3       Unsatisfied                30           50
4  Very Unsatisfied                20           50


3. Performs the Chi-Square test for independence.

4. Prints the Chi-Square statistic, degrees of freedom, p-value, and expected frequencies.


In [33]:
# perform Chi-Square test
chi2, p, dof, expected = stats.chi2_contingency(contingency_table)

# Print the results
print(f"Chi-Square Statistic: {np.round(chi2)}")
print(f"Degrees of Freedom: {dof}")
print(f"p-value: {np.round(p,2)}")
print("Expected Frequencies:")
print(expected)

Chi-Square Statistic: 20.0
Degrees of Freedom: 16
p-value: 0.22
Expected Frequencies:
[[0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]]


5. Print Critical value

In [34]:
# Critical value
alpha = 0.05
critical_value = stats.chi2.ppf(1 - alpha, dof)
print(f"Critical Value: {np.round(critical_value,2)}")

Critical Value: 26.3


6. Compares the Chi-Square statistic with the critical value to determine if we should reject the null hypothesis.

In [35]:
# Decision
if chi2 > critical_value:
    print("Reject the null hypothesis. There is a significant association between the type of device and customer satisfaction.")
else:
    print("Fail to reject the null hypothesis. There is no significant association between the type of device and customer satisfaction.")

Fail to reject the null hypothesis. There is no significant association between the type of device and customer satisfaction.
